os:
#  - osx
  - linux

dist: trusty
language: python
sudo: required

env:
  - ANSIBLE_VERSION=2.0.0.0
  - ANSIBLE_VERSION=2.0.1.0
  - ANSIBLE_VERSION=2.0.2.0
  - ANSIBLE_VERSION=2.1.0.0
  - ANSIBLE_VERSION=2.1.1.0
  - ANSIBLE_VERSION=2.1.2.0
  - ANSIBLE_VERSION=2.1.3.0

before_install:
  - 'if [ "$TRAVIS_OS_NAME" = "osx" ] ; then brew install bats ; fi'
  - 'if [ "$TRAVIS_OS_NAME" = "linux" ] ; then git clone https://github.com/sstephenson/bats.git ; fi'
  - 'if [ "$TRAVIS_OS_NAME" = "linux" ] ; then cd bats ; fi'
  - 'if [ "$TRAVIS_OS_NAME" = "linux" ] ; then sudo ./install.sh /usr/local ; fi'
  - 'if [ "$TRAVIS_OS_NAME" = "linux" ] ; then cd .. ; fi'

install:
  - pip install ansible==$ANSIBLE_VERSION
  - python setup.py install

script:
  - cd tests_bats
  - bats *.bats
